project               = "europan-world"
service_account_email = "vm-runtime@europan-world.iam.gserviceaccount.com"
region                = "us-west1"
zone                  = "us-west1-b"
machine_type          = "e2-highcpu-4"
machine_name          = "europa"
image_family          = "debian-11"
image_project         = "debian-cloud"